
/run/initialize

/Shower/detector/material G4_BRASS
/Shower/field/value 0

/tracking/verbose 0

#/Shower/stepping/ntuple false

#/Shower/generator/momentum 2
#/analysis/setFileName Shower_p_2000MeV_Brass_histo
#/run/beamOn 100

/Shower/stepping/ntuple true

#/Shower/generator/momentum 0.5
#/analysis/setFileName Shower_p_0500MeV_Brass
#/run/beamOn 10

/Shower/generator/momentum 1.0
/analysis/setFileName Shower_p_1000MeV_Brass
/run/beamOn 10
